package com.ruralops.platform.governance.domain;

import jakarta.persistence.*;

import java.time.Instant;

/**
 * Represents an Assembly Constituency within a District.
 *
 * A Constituency belongs to one District.
 * The combination of (district_id, name) must be unique.
 */
@Entity
@Table(
        name = "constituencies",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"district_id", "name"})
        }
)
public class Constituency {

    /**
     * Public governance identifier.
     *
     * Example: VZE-4721, AKP-3389
     * This ID is assigned externally and is not generated by the database.
     */
    @Id
    @Column(length = 15, nullable = false)
    private String id;

    /**
     * Parent District.
     *
     * Defines the administrative hierarchy.
     * A Constituency cannot exist without a District.
     */
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "district_id", nullable = false)
    private District district;

    /**
     * Official constituency name.
     *
     * Must be unique within the same District.
     */
    @Column(nullable = false, length = 120)
    private String name;

    /**
     * Indicates whether the Constituency is active.
     *
     * Used for soft disabling instead of deleting the record.
     */
    @Column(nullable = false)
    private boolean active = true;

    /**
     * Timestamp when the record was created.
     *
     * Set during construction and not updated later.
     */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Default constructor required by JPA.
     */
    public Constituency() {
        // For JPA
    }

    /**
     * Creates a new Constituency instance.
     *
     * @param id       Public governance ID
     * @param district Parent District
     * @param name     Official constituency name
     */
    public Constituency(String id, District district, String name) {
        this.id = id;
        this.district = district;
        this.name = name;
        this.createdAt = Instant.now();
    }

    public String getId() {
        return id;
    }

    public District getDistrict() {
        return district;
    }

    public String getName() {
        return name;
    }

    public boolean isActive() {
        return active;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setDistrict(District district) {
        this.district = district;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
