package com.ruralops.platform.governance.domain;

import jakarta.persistence.*;

import java.time.Instant;

/**
 * Represents a District within a State.
 *
 * A District belongs to one State.
 * The combination of (state_id, name) must be unique.
 */
@Entity
@Table(
        name = "districts",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"state_id", "name"})
        }
)
public class District {

    /**
     * Public governance identifier.
     *
     * Example: VSP-1268
     * This ID is assigned externally and is not generated by the database.
     */
    @Id
    @Column(length = 15, nullable = false)
    private String id;

    /**
     * Parent State.
     *
     * Defines the administrative hierarchy.
     * A District cannot exist without a State.
     */
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "state_id", nullable = false)
    private State state;

    /**
     * Official district name.
     *
     * Must be unique within the same State.
     */
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Indicates whether the District is active.
     *
     * Used for soft disabling instead of deleting the record.
     */
    @Column(nullable = false)
    private boolean active = true;

    /**
     * Timestamp when the record was created.
     *
     * Set during construction and not updated later.
     */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Default constructor required by JPA.
     */
    public District() {
        // For JPA
    }

    /**
     * Creates a new District instance.
     *
     * @param id    Public governance ID
     * @param state Parent State
     * @param name  Official district name
     */
    public District(String id, State state, String name) {
        this.id = id;
        this.state = state;
        this.name = name;
        this.createdAt = Instant.now();
    }

    // ---- Read-only getters ----

    public String getId() {
        return id;
    }

    public State getState() {
        return state;
    }

    public String getName() {
        return name;
    }

    public boolean isActive() {
        return active;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setState(State state) {
        this.state = state;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
