package com.ruralops.platform.governance.domain;

import jakarta.persistence.*;

import java.time.Instant;

/**
 * Represents a Village within a Mandal.
 *
 * A Village belongs to one Mandal.
 * The combination of (mandal_id, name) must be unique.
 */
@Entity
@Table(
        name = "villages",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"mandal_id", "name"})
        }
)
public class Village {

    /**
     * Public governance identifier.
     *
     * Example: PNP-4831, ALM-7294
     * This ID is assigned externally and is not generated by the database.
     */
    @Id
    @Column(length = 20, nullable = false)
    private String id;

    /**
     * Parent Mandal.
     *
     * Defines the administrative hierarchy.
     * A Village cannot exist without a Mandal.
     */
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "mandal_id", nullable = false)
    private Mandal mandal;

    /**
     * Official village name.
     *
     * Must be unique within the same Mandal.
     */
    @Column(nullable = false, length = 120)
    private String name;

    /**
     * Indicates whether the Village is active.
     *
     * Used for soft disabling instead of deleting the record.
     */
    @Column(nullable = false)
    private boolean active = true;

    /**
     * Timestamp when the record was created.
     *
     * Set during construction and not updated later.
     */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Default constructor required by JPA.
     */
    public Village() {
        // For JPA
    }

    /**
     * Creates a new Village instance.
     *
     * @param id     Public governance ID
     * @param mandal Parent Mandal
     * @param name   Official village name
     */
    public Village(String id, Mandal mandal, String name) {
        this.id = id;
        this.mandal = mandal;
        this.name = name;
        this.createdAt = Instant.now();
    }

    public String getId() {
        return id;
    }

    public Mandal getMandal() {
        return mandal;
    }

    public String getName() {
        return name;
    }

    public boolean isActive() {
        return active;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setMandal(Mandal mandal) {
        this.mandal = mandal;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
